---
title: "NO2 Comparison"
author: "Keita Ebisu"
date: "4/14/2020"
output: html_document
---


```{r cars, include=FALSE}
pacman::p_load(tidyverse)
```


```{r pressure, echo=TRUE}
load('K:/Research/People/Jesse/COVID19/CovID19/Data/Jesse/NO2CountyPastYearDF.RData')
load('K:/Research/People/Jesse/COVID19/CovID19/Data/Jesse/NO2CountyDF.RData')

BasicInfo = df.no2.county %>% 
       distinct(GEOID, .keep_all = TRUE) %>% 
       select(GEOID, Pop2010:NonEssentialServiceClose) %>% 
       mutate(Closed.Timing = ifelse(as.Date(NonEssentialServiceClose) >= as.Date('2020-03-25') | is.na(NonEssentialServiceClose),'Later', 'Early'))

ref.period2 = c(seq(as.Date('2017-03-13'),as.Date('2017-04-08'), 'day'),
               seq(as.Date('2018-03-13'),as.Date('2018-04-08'), 'day'),
               seq(as.Date('2019-03-13'),as.Date('2019-04-08'), 'day'))

Close.date = df.no2.county.pastyears %>% 
       filter(Date %in% ref.period2) %>% 
       rename(Date2 = Date) %>% 
       mutate(Period = 'Past')

df = df.no2.county %>% 
       mutate(Period = 'Current') %>% 
       filter(as.Date(Date2) >= as.Date('2020-03-13')) %>% 
       select(GEOID, Date2, NO2, Period) %>% 
       rbind(Close.date) %>% 
       mutate(Year = substr(Date2, 1, 4)) %>% 
       inner_join(BasicInfo, by = 'GEOID') 
df %>% 
       group_by(GEOID, Period) %>% 
       summarize(NO2 = mean(NO2, na.rm = TRUE)) %>% 
       pivot_wider(names_from = Period, values_from = NO2) %>% 
       filter(!is.na(Current), !is.na(Past)) %>% 
       inner_join(BasicInfo, by = 'GEOID') %>% 
       ggplot() +
              geom_point(aes(x = Past, y = Current, color = Urbanicity2), size =2) +
              geom_abline(slope = 1) +
              xlim(0, 40) +
              ylim(0, 40) +
              ggtitle(expression(NO[2]*' comparison (March 13th ~ April 8th) ')) +
              theme_bw() +
              theme(plot.title = element_text(hjust = 0.5))


```

Summary statistics as well as conducting a paired ttest
```{r}
plot.data = df %>% 
       group_by(GEOID, Period) %>% 
       summarize(NO2 = mean(NO2, na.rm = TRUE)) %>% 
       pivot_wider(names_from = Period, values_from = NO2) %>% 
       filter(!is.na(Current), !is.na(Past)) %>% 
       inner_join(BasicInfo, by = 'GEOID') 

dim(plot.data)
summary(plot.data$Current)
summary(plot.data$Past)

t.test(plot.data$Current, plot.data$Past, paired = TRUE)

plot.data.early = plot.data %>% 
       filter(Closed.Timing == 'Early')
t.test(plot.data.early$Current, plot.data.early$Past, paired = TRUE)

plot.data.later = plot.data %>% 
       filter(Closed.Timing == 'Later')
t.test(plot.data.later$Current, plot.data.later$Past, paired = TRUE)

```

Scatter Plot stratified by timing
```{r}
ggplot(data = plot.data) +
       geom_point(aes(x = Past, y = Current, color = Urbanicity), size =2) +
       geom_abline(slope = 1) +
       facet_wrap(~Closed.Timing) +
       xlim(0, 40) +
       ylim(0, 40) +
       ggtitle(expression(NO[2]*' comparison (March 13th ~ April 8th) stratified by Non-essential Closure Status')) +
       ylab(expression('Mean '*PM[2.5]*' during Covid 2020')) +
       xlab(expression('Historical Mean '*PM[2.5])) +
       theme_bw() +
       theme(plot.title = element_text(hjust = 0.5))

```

